### ISSUE TITLE
ROADMAP - ovos-utils 0.1.0

### ISSUE THREAD

**Issue by NeonDaniel** [OpenVoiceOS/ovos-utils#117]
Things to do before releasing 0.1.0
- [x]  https://github.com/OpenVoiceOS/ovos-utils/pull/208 launch last alpha with deprecation warnings before 0.1.0
- [x] https://github.com/OpenVoiceOS/ovos-utils/pull/204 remove all dead code
- [x] https://github.com/OpenVoiceOS/OVOS-workshop/pull/153 move some stuff to ovos workshop
- [x] https://github.com/OpenVoiceOS/ovos-mark1-utils move mark1 to dedicated repo
- [x] https://github.com/OpenVoiceOS/ovos-bus-client/pull/66 move some stuff to ovos bus client
- [x] https://github.com/OpenVoiceOS/ovos-bus-client/pull/67  move some stuff to ovos bus client
- [x] https://github.com/OpenVoiceOS/ovos-plugin-manager/pull/196 move some stuff to ovos plugin manager
- [x] https://github.com/OpenVoiceOS/ovos-utils/issues/205
- [x] https://github.com/OpenVoiceOS/ovos-utils/pull/81
- [x] https://github.com/OpenVoiceOS/ovos-bus-client/pull/68
- [x] https://github.com/OpenVoiceOS/ovos-utils/pull/207
- [x] https://github.com/OpenVoiceOS/ovos-config/pull/90
- [x] https://github.com/OpenVoiceOS/ovos-utils/pull/206
- [ ] https://github.com/OpenVoiceOS/ovos-utils/issues/2
- [x] https://github.com/OpenVoiceOS/ovos-utils/pull/203

**Comment by NeonDaniel** [comment]
Planning this release, breaking changes mean we should be certain there is no `~=0.0` dependency reference in any stable package before pushing a breaking change to `0.1.0` unless we've explicitly tested that package with the latest ovos-utils alpha

**Comment by goldyfruit** [comment]
PAHL is using `ovos-utils~=0.0, >=0.0.31a6`

**Comment by goldyfruit** [comment]
Do we want to keep the `PIDLock`? https://github.com/OpenVoiceOS/ovos-messagebus/issues/4

**Comment by JarbasAl** [comment]
I say we should just stop using it everywhere, but PIDLock can remain here as it might be useful in the future

**Comment by JarbasAl** [comment]
https://github.com/OpenVoiceOS/ovos-utils/pull/237
